version: "3"

services:
  jenkins:
    image: jenkins/jenkins
    network_mode: host
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    volumes:
      - /opt/jenkins_home:/var/jenkins_home 
    restart: unless-stopped